### ISSUE TITLE
IP address `::1` needs to be included in allowed_ips

### ISSUE THREAD

**Issue by CyberGrating** [adfinis/ansible-collection-maintenance#21]
The `adfinis/maintenance/plugins/modules/lastlogins.py` file includes IP address of `0.0.0.0` as apart of `allowed_ips`. The same needs to be done for IP `::1`.

From output on one machine:
```
+root     pts/1        ::1              Mon Aug  1 08:11:59 2022 - Mon Aug  1 08:12:05 2022  (00:00)
```

**Comment by s3lph** [comment]
Are you sure that's actually a bug in lastlogins, and not just someone running `ssh root@localhost`? I could not find any reference whatsoever to `::1` being used in wtmp to indicate a locally started (i.e. without network involvement) login session. Or am I just missing something here?

I'm not sure whether we should exclude localhost ssh logins in a hardcoded fashion; it's not something I'd consider "normal behavior". If localhost ssh login is a non-issue for that host, please add `::1` and any IPv4 equivalents to `allowed_ips` in host_vars. @SaschaD-Adfinis do you agree?

**Comment by s3lph** [comment]
@CyberGrating is this still an open issue?

**Comment by CyberGrating** [comment]
This is an output from one of our servers:
```
TASK [adfinis.maintenance.maintenance_10_linux : 10-041: Security: Logins: Are there logins from suspicious hosts/users? | Gather past logins from `last` output] ***
--- before
+++ after
@@ -0,0 +1,3 @@
+root     pts/1        ::1              Thu May 26 00:13:38 2022 - Thu May 26 00:13:41 2022  (00:00)
+root     pts/1        ::1              Fri May  6 02:20:28 2022 - Fri May  6 02:20:32 2022  (00:00)
```
These should valid login/host, not marked as "suspicious"

**Comment by Melkor333** [comment]
> This is an output from one of our servers:
> 
> ```
> TASK [adfinis.maintenance.maintenance_10_linux : 10-041: Security: Logins: Are there logins from suspicious hosts/users? | Gather past logins from `last` output] ***
> --- before
> +++ after
> @@ -0,0 +1,3 @@
> +root     pts/1        ::1              Thu May 26 00:13:38 2022 - Thu May 26 00:13:41 2022  (00:00)
> +root     pts/1        ::1              Fri May  6 02:20:28 2022 - Fri May  6 02:20:32 2022  (00:00)
> ```
> 
> These should valid login/host, not marked as "suspicious"

I assume that these logins were from a maintainer doing `ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no root@localhost` to test if the root password is still valid. But I kinda agree with @s3lph that it's probably reasonable to not ignore these IPs per default and add them to the `groups_vars/host_vars` instead, because it IS weird and I can imagine that local ssh could be used in of some kind of exploit-chaining (e.g. get an unprivileged shell via an apache/nginx exploit and then use local ssh to get root, which circumvents an IP-Whitelist on port 22). Certainly a *very* specific scenario though  😅
@SaschaD-Adfinis You might have some opinions on this aswell... If we don't want to ignore `::1` per default we should make sure we don't use the `ssh ... localhost` command (anymore)
