### ISSUE TITLE
10-051 - no error handling :bug: 

### ISSUE THREAD

**Issue by jamiemoller** [adfinis/ansible-collection-maintenance#3]
when postalias is not installed all subsequent check fail

**Comment by s3lph** [comment]
The task is **supposed** to fail if postfix is not installed, because postfix is (resp. was) expected to be installled on our systems.

If a system does not have postfix installed, the correct approach is to exclude the postfix-related checks on the affected host:

`host_vars/example.tux42.ch/main.yml`:
```yaml
---

maintenance_exclude_tasks:
  - 10-050
  - 10-051
```

But the documentation regarding this behavior could definitely improved. I'll update the documentation later  today.
