### ISSUE TITLE
Script doesn't find security repo for 11-011.

### ISSUE THREAD

**Issue by CyberGrating** [adfinis/ansible-collection-maintenance#38]
Output for 11-011 shows script is trying to find the file `/etc/apt/sources.list.d/security_debian_org_debian_security.list` which doesn't exist and thus can't find the line with the security repo entry.

The issue is that the [ansible.builtin.apt_repository module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_repository_module.html#ansible-collections-ansible-builtin-apt-repository-module) wants a `filename` and if none is given, it will create a default filename instead.

The check shouldn't rely on a particular filename and instead search all `source` files for the repo entry. Perhaps another method can be found rather than using this module???

**Comment by s3lph** [comment]
Hi @CyberGrating 

The filename in `ansible.builtin.apt_repository` is only used when adding the repository. If it's already present in **any** sources.list file, the module recognizes this instead of creating the new file.

If you're seeing a host where the playbook suggests that `/etc/apt/sources.list.d/security_debian_org_debian_security.list` would be created, this means that debian-security wasn't found in any sources.list file. This does not mean that it **must** be created at that specific path in order for it to be detected.
